"""empty message

Revision ID: 1039e4baf2c8
Revises: None
Create Date: 2014-05-27 20:59:42.783437

"""

# revision identifiers, used by Alembic.
revision = '1039e4baf2c8'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('seotitle', sa.String(length=128), nullable=True),
    sa.Column('seokey', sa.String(length=128), nullable=True),
    sa.Column('seodesc', sa.String(length=300), nullable=True),
    sa.Column('thumbnail', sa.String(length=255), nullable=True),
    sa.Column('template', sa.String(length=255), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('body_html', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tags_name'), 'tags', ['name'], unique=True)
    op.create_table('links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('anchor', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=True),
    sa.Column('url', sa.String(length=255), nullable=False),
    sa.Column('note', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('labels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=32), nullable=False),
    sa.Column('title', sa.Unicode(length=100), nullable=False),
    sa.Column('html', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('redirects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('old_path', sa.String(length=128), nullable=False),
    sa.Column('new_path', sa.String(length=128), nullable=False),
    sa.Column('note', sa.String(length=400), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('friendlinks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('anchor', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=True),
    sa.Column('url', sa.String(length=255), nullable=False),
    sa.Column('actived', sa.Boolean(), nullable=True),
    sa.Column('note', sa.String(length=400), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('flatpages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=32), nullable=False),
    sa.Column('title', sa.Unicode(length=100), nullable=False),
    sa.Column('seotitle', sa.Unicode(length=200), nullable=True),
    sa.Column('seokey', sa.Unicode(length=128), nullable=True),
    sa.Column('seodesc', sa.Unicode(length=400), nullable=True),
    sa.Column('template', sa.String(length=255), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('body_html', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('longslug', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('seotitle', sa.String(length=128), nullable=True),
    sa.Column('seokey', sa.String(length=128), nullable=True),
    sa.Column('seodesc', sa.String(length=300), nullable=True),
    sa.Column('thumbnail', sa.String(length=255), nullable=True),
    sa.Column('template', sa.String(length=255), nullable=True),
    sa.Column('article_template', sa.String(length=255), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('body_html', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categories_longslug'), 'categories', ['longslug'], unique=True)
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('default', sa.Boolean(), nullable=True),
    sa.Column('permissions', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_roles_default'), 'roles', ['default'], unique=False)
    op.create_table('topics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('seotitle', sa.String(length=128), nullable=True),
    sa.Column('seokey', sa.String(length=128), nullable=True),
    sa.Column('seodesc', sa.String(length=300), nullable=True),
    sa.Column('thumbnail', sa.String(length=255), nullable=True),
    sa.Column('template', sa.String(length=255), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('body_html', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_topics_slug'), 'topics', ['slug'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('confirmed', sa.Boolean(), nullable=True),
    sa.Column('about_me', sa.String(length=1000), nullable=True),
    sa.Column('member_since', sa.DateTime(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('avatar_hash', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], [u'roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('articles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('seotitle', sa.String(length=200), nullable=True),
    sa.Column('seokey', sa.String(length=128), nullable=True),
    sa.Column('seodesc', sa.String(length=300), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=True),
    sa.Column('thumbnail', sa.String(length=255), nullable=True),
    sa.Column('thumbnail_big', sa.String(length=255), nullable=True),
    sa.Column('template', sa.String(length=255), nullable=True),
    sa.Column('summary', sa.String(length=2000), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('body_html', sa.Text(), nullable=True),
    sa.Column('published', sa.Boolean(), nullable=True),
    sa.Column('ontop', sa.Boolean(), nullable=True),
    sa.Column('recommend', sa.Boolean(), nullable=True),
    sa.Column('hits', sa.Integer(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('last_modified', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], [u'users.id'], ),
    sa.ForeignKeyConstraint(['category_id'], [u'categories.id'], ),
    sa.ForeignKeyConstraint(['topic_id'], [u'topics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('article_tags',
    sa.Column('article_id', sa.Integer(), nullable=True),
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('article_tags')
    op.drop_table('articles')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_topics_slug'), table_name='topics')
    op.drop_table('topics')
    op.drop_index(op.f('ix_roles_default'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_categories_longslug'), table_name='categories')
    op.drop_table('categories')
    op.drop_table('flatpages')
    op.drop_table('friendlinks')
    op.drop_table('redirects')
    op.drop_table('labels')
    op.drop_table('links')
    op.drop_index(op.f('ix_tags_name'), table_name='tags')
    op.drop_table('tags')
    ### end Alembic commands ###
