"""empty message

Revision ID: 573c11d104ad
Revises: 1039e4baf2c8
Create Date: 2014-08-21 13:55:26.875589

"""

# revision identifiers, used by Alembic.
revision = '573c11d104ad'
down_revision = '1039e4baf2c8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('friendlinks', sa.Column('order', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('friendlinks', 'order')
    ### end Alembic commands ###
